import Head from "next/head";
import requests from "@/utilits/requests";
import Header from "@/components/Header";
import { Fragment } from "react";
import Nav from "@/components/Nav";
import Results from "@/components/Results";

export default function Home({ moviesData }) {
  return (
    <Fragment>
      <Head>
        <title>Hulu-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />

      <Results movies={moviesData} />
    </Fragment>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `${requests[genre]?.url || requests.fetchTrending.url} `
  );
  const data = await request.json();

  return {
    props: {
      moviesData: data,
    },
  };
}
